-- Sesion(key, timeout)

-- Objeto(sesionKey, clase, data)


CREATE TABLE "Session" (
	SESSIONKEY INTEGER NOT NULL IDENTITY,
	TIMEOUT INTEGER,
	CONSTRAINT SYS_PK_10157 PRIMARY KEY (SESSIONKEY)
);

CREATE TABLE "Object" (
	OBJECTKEY INTEGER NOT NULL IDENTITY,
	SESSIONKEY INTEGER,
	CLASS VARCHAR(255),
	"DATA" VARCHAR(255),
	CONSTRAINT SYS_PK_10196 PRIMARY KEY (OBJECTKEY)
);


ALTER TABLE "Object" 
ADD CONSTRAINT OBJECT_FK 
FOREIGN KEY (SESSIONKEY) REFERENCES "Session"(SESSIONKEY);
