-- Sesion(key, timeout)

-- Objeto(sesionKey, clase, data)

CREATE TABLE "SESSIONS" (
	SESSION_KEY INTEGER NOT NULL PRIMARY KEY,
	TIMEOUT INTEGER,
);

CREATE TABLE "PERSISTENT_OBJECT" (
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	SESSION_KEY INTEGER,
	CLASS_NAME VARCHAR(255),
	"DATA" VARCHAR(255),
	FOREIGN KEY (SESSION_KEY) REFERENCES SESSIONS(SESSION_KEY) ON DELETE CASCADE
);